version: '3.7'
services:
  frontend:
    image: maccpr7/frontend:latest
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  backend:
    image: maccpr7/backend:latest
    build: ./backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
      TEST_DATABASE_URI: ${TEST_DATABASE_URI}
  mysql:
    image: maccpr7/database:latest
    build: ./database
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
